export interface Product {
  id: string;
  name: string;
  slug: string;
  category: string;
  color: string;
  price: number;
  images: string[];
  sizes: string[];
  colors: string[];
  isNew: boolean;
  stock: number;
  description: string;
}

export const PRODUCTS: Product[] = [
  {
    id: "gym-vest-brown",
    name: "GYM VEST",
    slug: "gym-vest-brown",
    category: "VESTS",
    color: "Brown",
    price: 899,
    images: ["/products/ribbed_vest_brown_1.jpeg", "/products/ribbed_vest_brown_2.jpeg"],
    sizes: ["S", "M", "L"],
    colors: ["Brown"],
    isNew: true,
    stock: 100,
    description: "Performance gym vest engineered for unrestricted movement. Moisture-wicking fabric. Street-ready cut.",
  },
  {
    id: "gym-vest-black",
    name: "GYM VEST",
    slug: "gym-vest-black",
    category: "VESTS",
    color: "Black",
    price: 899,
    images: ["/products/ribbed_vest_black_1.jpeg", "/products/ribbed_vest_black_2.jpeg"],
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    isNew: true,
    stock: 100,
    description: "Performance gym vest engineered for unrestricted movement. Moisture-wicking fabric. Street-ready cut.",
  },
  {
    id: "gym-vest-grey",
    name: "GYM VEST",
    slug: "gym-vest-grey",
    category: "VESTS",
    color: "Grey",
    price: 899,
    images: [],
    sizes: ["S", "M", "L"],
    colors: ["Grey"],
    isNew: true,
    stock: 100,
    description: "Performance gym vest engineered for unrestricted movement. Moisture-wicking fabric. Street-ready cut.",
  },
  {
    id: "gym-vest-white",
    name: "GYM VEST",
    slug: "gym-vest-white",
    category: "VESTS",
    color: "White",
    price: 899,
    images: ["/products/ribbed_vest_white_1.jpeg", "/products/ribbed_vest_white_2.jpeg"],
    sizes: ["S", "M", "L"],
    colors: ["White"],
    isNew: true,
    stock: 100,
    description: "Performance gym vest engineered for unrestricted movement. Moisture-wicking fabric. Street-ready cut.",
  },
  {
    id: "compression-half-brown",
    name: "COMPRESSION HALF SLEEVE",
    slug: "compression-half-brown",
    category: "COMPRESSION",
    color: "Brown",
    price: 1199,
    images: [],
    sizes: ["S", "M", "L"],
    colors: ["Brown"],
    isNew: true,
    stock: 100,
    description: "Second-skin compression half sleeve. Supports muscle groups during peak performance. Wears like armour.",
  },
  {
    id: "compression-half-black",
    name: "COMPRESSION HALF SLEEVE",
    slug: "compression-half-black",
    category: "COMPRESSION",
    color: "Black",
    price: 1199,
    images: ["/products/gymkha_performance_compression_black_1.jpeg", "/products/gymkha_performance_compression_black_4.jpeg"],
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    isNew: true,
    stock: 100,
    description: "Second-skin compression half sleeve. Supports muscle groups during peak performance. Wears like armour.",
  },
  {
    id: "compression-half-grey",
    name: "COMPRESSION HALF SLEEVE",
    slug: "compression-half-grey",
    category: "COMPRESSION",
    color: "Grey",
    price: 1199,
    images: [],
    sizes: ["S", "M", "L"],
    colors: ["Grey"],
    isNew: true,
    stock: 100,
    description: "Second-skin compression half sleeve. Supports muscle groups during peak performance. Wears like armour.",
  },
  {
    id: "compression-half-white",
    name: "COMPRESSION HALF SLEEVE",
    slug: "compression-half-white",
    category: "COMPRESSION",
    color: "White",
    price: 1199,
    images: ["/products/gymkha_performance_compression_white_1.jpeg", "/products/gymkha_performance_compression_white_4.jpeg"],
    sizes: ["S", "M", "L"],
    colors: ["White"],
    isNew: true,
    stock: 100,
    description: "Second-skin compression half sleeve. Supports muscle groups during peak performance. Wears like armour.",
  },
  {
    id: "compression-full-brown",
    name: "COMPRESSION FULL SLEEVE",
    slug: "compression-full-brown",
    category: "COMPRESSION",
    color: "Brown",
    price: 1099,
    images: [],
    sizes: ["S", "M", "L"],
    colors: ["Brown"],
    isNew: true,
    stock: 100,
    description: "Full sleeve compression built for cold sessions and maximum muscle support. From iron to streets.",
  },
  {
    id: "compression-full-black",
    name: "COMPRESSION FULL SLEEVE",
    slug: "compression-full-black",
    category: "COMPRESSION",
    color: "Black",
    price: 1099,
    images: ["/products/full_sleeve_compression_tee_black_1.jpeg", "/products/full_sleeve_compression_tee_black_2.jpeg"],
    sizes: ["S", "M", "L"],
    colors: ["Black"],
    isNew: true,
    stock: 100,
    description: "Full sleeve compression built for cold sessions and maximum muscle support. From iron to streets.",
  },
  {
    id: "compression-full-grey",
    name: "COMPRESSION FULL SLEEVE",
    slug: "compression-full-grey",
    category: "COMPRESSION",
    color: "Grey",
    price: 1099,
    images: [],
    sizes: ["S", "M", "L"],
    colors: ["Grey"],
    isNew: true,
    stock: 100,
    description: "Full sleeve compression built for cold sessions and maximum muscle support. From iron to streets.",
  },
  {
    id: "compression-full-white",
    name: "COMPRESSION FULL SLEEVE",
    slug: "compression-full-white",
    category: "COMPRESSION",
    color: "White",
    price: 1099,
    images: ["/products/full_sleeve_compression_tee_white_1.jpeg", "/products/full_sleeve_compression_tee_white_2.jpeg"],
    sizes: ["S", "M", "L"],
    colors: ["White"],
    isNew: true,
    stock: 100,
    description: "Full sleeve compression built for cold sessions and maximum muscle support. From iron to streets.",
  },
  {
    id: "gym-towel",
    name: "GYM TOWEL",
    slug: "gym-towel",
    category: "ACCESSORIES",
    color: "Charcoal",
    price: 299,
    images: [],
    sizes: ["ONE SIZE"],
    colors: ["Charcoal"],
    isNew: false,
    stock: 100,
    description: "Microfiber gym towel. Ultra-absorbent. Compact. PRISM branded.",
  },
];
